### PR TITLE
Added Google Quiz

### PR DESCRIPTION
**Pull request by U-Jayadhar**
Signed-off-by: Jayadhar Ummadisingu <142038252+U-Jayadhar@users.noreply.github.com>

### CODE REVIEW

**Comment by ManasMalla** [comment]
@U-Jayadhar Can you give me a little input on what's this PR fixing or implementing? 😊

**Comment by U-Jayadhar** [comment]
### Added New Quiz: "Google Guru" to Arcade Page
- Created and added the necessary JSON and Vue files for the new quiz.
- The quiz is now part of the Arcade Page, a fun quiz that tests the player knowledge in Google.

Screenshot 2024-11-09 000043
Screenshot 2024-11-09 000052
Screenshot 2024-11-09 000108

**Comment by ManasMalla** [comment]
@U-Jayadhar 
### **TODOs:**
1. Replace the key for local storage saving scores and other variables for quiz
2. Update the images and placeholders
3. Read scores and variables from firebase and update keybindings

**Comment by U-Jayadhar** [comment]
@ManasMalla Done with the TODOs

Check and review them.

image

image

**Review by ManasMalla — APPROVED** [review]
LGTM;

**Comment by ManasMalla** [comment]
@U-Jayadhar there seem to be merge conflicts can you rebase them?

**Pull request merged**
